apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-headless
  labels: {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-kafka
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: kafka
    {{- if .Values.auth.ssl }}
    - name: tls-kafka
      port: {{ .Values.service.sslPort }}
      protocol: TCP
      targetPort: kafka-ssl
    {{- end }}
  selector: {{- include "kafka.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
